services:
  postgres:
    image: postgres:15.1
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgres_microservice_back_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    restart: unless-stopped
    ports:
      - 5434:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin

  minio:
    image: minio/minio
    command: server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin228
      MINIO_ROOT_PASSWORD: admin228

volumes:
  pgadmin:
  postgres_microservice_back_auth:
  minio_storage:
